# Generated by Django 4.0.6 on 2022-07-10 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_links_delete_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 10, 23, 28, 17, 900180)),
        ),
    ]
